name: Build container

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install ssh key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Adding rclone config
        run: |
          mkdir -p ~/.config/rclone
          echo "${{ secrets.RCLONE_CONF }}" > ~/.config/rclone/rclone.conf

      - name: Build container on remote
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "sbatch --wait <<EOT
          #!/bin/bash
          #SBATCH -J singularity-build
          #SBATCH -o .ci-build.log
          #SBATCH -t 20
          #SBATCH --mem=8G

          set -e
          recipe=\$(mktemp)
          cat > \$recipe << RECIPE
          ${{ secrets.RECIPE }}
          RECIPE
          rclone copy singularity-build \$recipe \${{ secrets.COLLECTION_CONTAINER }}
          singularity build --fakeroot \${{ secrets.CONTAINER_NAME }}.simg \$recipe
          rclone copy \${{ secrets.CONTAINER_NAME }}.simg \${{ secrets.COLLECTION_CONTAINER }}
          EOT"
