name: Build Container

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install ssh key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Adding rclone config
        run: |
          mkdir -p ~/.config/rclone
          echo "${{ secrets.RCLONE_CONF }}" > ~/.config/rclone/rclone.conf

      - name: Build container on remote HPC
        run: |
          ssh -o ServerAliveInterval=60 ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "sbatch --wait <<EOT
          #!/bin/bash
          #SBATCH -J singularity-build
          #SBATCH --output=.ci-build-%j.log
          #SBATCH --time=30
          #SBATCH --mem=16G

          set -e
          echo '--- Iniciando job no cluster (método echo robusto) ---'
          
          recipe_file=\$(mktemp)
          echo 'Criando arquivo de receita temporário...'
          
          echo -e \"\${{ secrets.RECIPE }}\" > \$recipe_file

          echo 'Construindo o container...'
          singularity build --fakeroot ${{ secrets.CONTAINER_NAME }}.sif \$recipe_file

          echo 'Enviando o container para a nuvem...'
          rclone copy --progress ${{ secrets.CONTAINER_NAME }}.sif '${{ vars.COLLECTION_CONTAINER }}'

          echo '--- Job no cluster finalizado com sucesso ---'
          EOT"
